### ISSUE TITLE
请求文件方法可能存在不安全因素

### ISSUE THREAD

**Issue by sparrowhe** [ItzJerry317/JrChat#1]
https://github.com/ItzJerry317/JrChat/blob/main/index.js#L46 处代码没有对传入 `pathname` 进行过滤，可能存在跨路径读取漏洞。

payload: `/home/xx/test.file`

**Comment by ItzJerry317** [comment]
好的，有时间会修复
（加密之类的）

**Comment by ItzJerry317** [comment]
可能修复会有些慢，本人js新手（）

**Comment by ItzJerry317** [comment]
已经加密了 希望这可以奏效
如果不行，随时reopen这个issue
